apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: usuarios-vs
  namespace: servicemesh
spec:
  hosts:
  - usuarios-service
  http:
  - route:
    - destination:
        host: usuarios-service
        subset: v1
      weight: 100 #100% del tráfico a v1
    #Timeouts y retries automáticos
    timeout: 5s
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: 5xx,reset,connect-failure
